# Sonocotta HiFi-ESP32-S3-Mic Hardware Profile
# PCM5100A DAC - Line-level output 2.1V + Microphone Header
# https://github.com/sonocotta/esp32-audio-dock
#
# ⚠️ This package contains ONLY hardware-specific settings.
# Add application logic (LED, IR, switches, EQ) in your main config.
#
# Compatible with: Rev G2 and later (S3 with mic header)
# For Rev G/G1 (without mic): Use hifi-esp32-s3.yaml
# Revision notes:
#   - LED: GPIO9 (standard for G2+)
#   - IR: GPIO7 (all S3 revisions)
#   - Mic pins: WS=GPIO17, BCK=GPIO18, DIN=GPIO8

substitutions:
  board_type: "HiFi-ESP32-S3-Mic"
  board_revision: "G2+"
  task_stack_in_psram: "true"  # ESP32-S3 requires true
  
  # Hardware pins:
  led_pin: "GPIO9"       # Standard for G2+
  ir_pin: "GPIO7"        # Standard for all S3 revisions
  mic_ws_pin: "GPIO17"   # Mic WS
  mic_bck_pin: "GPIO18"  # Mic BCK
  mic_din_pin: "GPIO8"   # Mic data input

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

# I2S Audio Configuration (Speaker output)
i2s_audio:
  i2s_lrclk_pin: GPIO15  # WS
  i2s_bclk_pin: GPIO14   # BCK
