# Sonocotta Louder-ESP32 Board Package (Rev H-H5)
# Hardware: TAS5805M DAC + Amplifier (25W @ 8Î©) with 15-band hardware EQ
# Compatible: Rev H through H5 (without mic header)
# For Rev H6: Use louder-esp32-mic.yaml
#
# Usage in your config:
#   packages:
#     board: !include boards/sonocotta/louder-esp32.yaml

substitutions:
  board_type: "Louder-ESP32"
  board_revision: "H-H5"
  
  # CRITICAL: Vanilla ESP32 requires false!
  task_stack_in_psram: "false"
  
  # Customizable pins
  led_pin: "GPIO27"      # Varies: GPIO9 (early), GPIO21 (mid), GPIO27 (late)
  ir_pin: "GPIO34"       # Default; GPIO35 or GPIO19 on some revisions

# ESP32 Hardware Configuration
esp32:
  board: esp32dev
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

# PSRAM Configuration
psram:
  mode: quad
  speed: 40MHz
  ignore_not_found: false

# I2C for TAS5805M DAC Control
i2c:
  sda: GPIO16
  scl: GPIO1
  frequency: 400kHz
  scan: true

# I2S Audio Pins
i2s_audio:
  i2s_lrclk_pin: GPIO22  # WS
  i2s_bclk_pin: GPIO26   # BCK
  # i2s_dout_pin: GPIO25  # Set in main config

# TAS5805M DAC Component
external_components:
  - source: github://mrtoy-me/esphome-tas5805m@main
    components: [ tas5805m ]
    refresh: 60s

# TAS5805M Configuration
audio_dac:
  - platform: tas5805m
    id: tas5805m_dac
    enable_pin: GPIO21      # PWDN pin
    dac_mode: BTL
    mixer_mode: STEREO
    analog_gain_left_db: 0
    analog_gain_right_db: 0
    volume_max: -1dB
    volume_min: -60dB
    refresh_eq: BY_SWITCH
    update_interval: 10s

# Board-specific switches
switch:
  - platform: tas5805m
    enable_dac:
      name: "${friendly_name} Enable DAC"
      id: enable_dac
      restore_mode: ALWAYS_OFF
    enable_eq:
      name: "${friendly_name} Enable EQ"
      id: enable_eq
      restore_mode: ALWAYS_OFF
