# Sonocotta Loud-ESP32 Hardware Profile
# Dual MAX98357 DAC - 3-5W per channel (direct speaker output)
# https://github.com/sonocotta/esp32-audio-dock
#
# ⚠️ This package contains ONLY hardware-specific settings.
# Add application logic (LED, IR, switches, EQ) in your main config.
#
# Compatible with: Multiple revisions
# Hardware: Two MAX98357A amplifiers for stereo output
# Revision notes:
#   - LED: GPIO4 (most common), GPIO12/GPIO21 on some revisions
#   - IR: GPIO32 (default), GPIO35 on some revisions
#   - ENABLE: GPIO13 (all revisions)

substitutions:
  board_type: "Loud-ESP32"
  task_stack_in_psram: "false"  # ESP32 requires false
  
  # Hardware pins:
  enable_pin: "GPIO13"   # MAX98357 ENABLE pin
  led_pin: "GPIO4"       # Default; some use GPIO12 or GPIO21
  ir_pin: "GPIO32"       # Default; some use GPIO35

esp32:
  board: esp32dev
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"

psram:
  mode: quad
  speed: 40MHz
  ignore_not_found: false

# I2S Audio Configuration
i2s_audio:
  i2s_lrclk_pin: GPIO22  # WS
  i2s_bclk_pin: GPIO26   # BCK
