# ============================================================
# Louder ESP32-S3 Plus - Board Profile (Hardware Only)
# ============================================================
# Board: Sonocotta Louder-ESP32-S3-Plus (Rev. K+)
# DAC: TAS5825M (I2C controlled, 24-bit 192kHz, 25W@8Î©)
# Features: 15-band hardware EQ, OLED display, RGB LED, IR, Ethernet
# 
# Hardware differences from standard Louder-ESP32-S3:
# - TAS5825M DAC (not TAS5805M)
# - Additional peripherals: RGB LED, IR receiver, SPI display
# - Ethernet (W5500) built-in
# ============================================================

substitutions:
  task_stack_in_psram: "true"  # MUST be true for ESP32-S3
  
  # I2C pins (for TAS5825M DAC control)
  i2c_sda_pin: GPIO8
  i2c_scl_pin: GPIO9
  
  # I2S audio pins
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14
  i2s_dout_pin: GPIO16
  
  # DAC control
  dac_enable_pin: GPIO17
  
  # RGB LED
  rgb_led_pin: GPIO21
  
  # IR receiver
  ir_rx_pin: GPIO07
  
  # SPI pins (for OLED display)
  spi_clk_pin: GPIO12
  spi_mosi_pin: GPIO11
  spi_miso_pin: GPIO13
  
  # Display control pins
  display_cs_pin: GPIO47
  display_dc_pin: GPIO38
  display_reset_pin: GPIO48
  
  # Ethernet pins (W5500)
  eth_cs_pin: GPIO10
  eth_interrupt_pin: GPIO6
  eth_reset_pin: GPIO5
  
  # DAC model
  dac_model: "TAS5825M"

esphome:
  platformio_options:
    board_build.flash_mode: dio
  # IMPORTANT: TAS5825M requires I2S clock signal before accepting DSP config
  # Play startup sound to initialize clock
  on_boot:
    priority: 220.0
    then:
      - media_player.play_media:
          id: media_player_id
          media_url: file://startup_sync_sound

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

debug:
  update_interval: 5s

# I2C for TAS5825M DAC control
i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  frequency: 400kHz
  scan: true
  timeout: 100us

# External component for TAS58xx series (includes TAS5825M)
external_components:
  - source: github://mrtoy-me/esphome-tas58xx@dev
    components: [ tas58xx ]
    refresh: 24h

# TAS5825M DAC configuration with hardware DSP
audio_dac:
  - platform: tas58xx
    id: tas58xx_dac
    tas58xx_dac: ${dac_model}
    enable_pin: ${dac_enable_pin}
    dac_mode: BTL          # Bridge Tied Load - 2Ch Stereo
    mixer_mode: STEREO     # Options: STEREO, STEREO_INVERSE, MONO, LEFT, RIGHT
    analog_gain: -6db      # -6dB = safer for 12V supply
    volume_min: -60dB      # Min volume mapping (goes to -103dB)
    update_interval: 5s    # Fault register check interval

# I2S audio interface
i2s_audio:
  i2s_lrclk_pin: ${i2s_lrclk_pin}
  i2s_bclk_pin: ${i2s_bclk_pin}

# DAC control switch
switch:
  - platform: tas58xx
    enable_dac:
      name: "Enable DAC"
      id: enable_dac
      restore_mode: ALWAYS_ON

# Hardware EQ controls (15 bands per channel, ISO frequencies)
number:
  - platform: tas58xx
    # Left channel EQ (20Hz - 16kHz)
    left_eq_gain_20Hz:
      name: "Left EQ 20Hz"
    left_eq_gain_31.5Hz:
      name: "Left EQ 31.5Hz"
    left_eq_gain_50Hz:
      name: "Left EQ 50Hz"
    left_eq_gain_80Hz:
      name: "Left EQ 80Hz"
    left_eq_gain_125Hz:
      name: "Left EQ 125Hz"
    left_eq_gain_200Hz:
      name: "Left EQ 200Hz"
    left_eq_gain_315Hz:
      name: "Left EQ 315Hz"
    left_eq_gain_500Hz:
      name: "Left EQ 500Hz"
    left_eq_gain_800Hz:
      name: "Left EQ 800Hz"
    left_eq_gain_1250Hz:
      name: "Left EQ 1.25kHz"
    left_eq_gain_2000Hz:
      name: "Left EQ 2kHz"
    left_eq_gain_3150Hz:
      name: "Left EQ 3.15kHz"
    left_eq_gain_5000Hz:
      name: "Left EQ 5kHz"
    left_eq_gain_8000Hz:
      name: "Left EQ 8kHz"
    left_eq_gain_16000Hz:
      name: "Left EQ 16kHz"
    
    # Right channel EQ
    right_eq_gain_20Hz:
      name: "Right EQ 20Hz"
    right_eq_gain_31.5Hz:
      name: "Right EQ 31.5Hz"
    right_eq_gain_50Hz:
      name: "Right EQ 50Hz"
    right_eq_gain_80Hz:
      name: "Right EQ 80Hz"
    right_eq_gain_125Hz:
      name: "Right EQ 125Hz"
    right_eq_gain_200Hz:
      name: "Right EQ 200Hz"
    right_eq_gain_315Hz:
      name: "Right EQ 315Hz"
    right_eq_gain_500Hz:
      name: "Right EQ 500Hz"
    right_eq_gain_800Hz:
      name: "Right EQ 800Hz"
    right_eq_gain_1250Hz:
      name: "Right EQ 1.25kHz"
    right_eq_gain_2000Hz:
      name: "Right EQ 2kHz"
    right_eq_gain_3150Hz:
      name: "Right EQ 3.15kHz"
    right_eq_gain_5000Hz:
      name: "Right EQ 5kHz"
    right_eq_gain_8000Hz:
      name: "Right EQ 8kHz"
    right_eq_gain_16000Hz:
      name: "Right EQ 16kHz"
    
    # Channel gain controls
    channel_gain_left:
      name: "Gain Left"
    channel_gain_right:
      name: "Gain Right"

# Fault monitoring sensors
sensor:
  - platform: tas58xx
    faults_cleared:
      name: "Faults Cleared Count"

# Fault detection binary sensors
binary_sensor:
  - platform: tas58xx
    have_fault:
      name: "Any Faults"
      exclude: CLOCK_FAULT  # Ignore I2S clock faults (normal during start/stop)
    left_channel_dc_fault:
      name: "Left DC Fault"
    right_channel_dc_fault:
      name: "Right DC Fault"
    left_channel_over_current:
      name: "Left Over Current"
    right_channel_over_current:
      name: "Right Over Current"
    otp_crc_check:
      name: "CRC Check Fault"
    bq_write_failed:
      name: "BQ Write Failure"
    pcdd_over_voltage:
      name: "PCDD Over Voltage"
    pcdd_under_voltage:
      name: "PCDD Under Voltage"
    over_temp_shutdown:
      name: "Over Temp Shutdown"
    over_temp_warning:
      name: "Over Temp Warning"
      id: over_temperature_warning

# Optional: Ethernet (W5500) - uncomment to use instead of WiFi
# ethernet:
#   type: W5500
#   clk_pin: ${spi_clk_pin}
#   mosi_pin: ${spi_mosi_pin}
#   miso_pin: ${spi_miso_pin}
#   cs_pin: ${eth_cs_pin}
#   interrupt_pin: ${eth_interrupt_pin}
#   reset_pin: ${eth_reset_pin}

# Optional: RGB LED (uncomment if installed)
# light:
#   - platform: esp32_rmt_led_strip
#     id: rgb_front_led
#     name: "${friendly_name} LED"
#     rgb_order: GRB
#     pin: ${rgb_led_pin}
#     num_leds: 1
#     chipset: ws2812
#     default_transition_length: 0s

# Optional: IR Receiver (uncomment if installed)
# remote_receiver:
#   pin: 
#     number: ${ir_rx_pin}
#     inverted: true
#     mode:
#       input: true
#   dump: all

# Optional: SPI for OLED display (uncomment if installed)
# spi:
#   clk_pin: ${spi_clk_pin}
#   mosi_pin: ${spi_mosi_pin}
#   miso_pin: ${spi_miso_pin}
#   id: spi_bus_display

# ============================================================
# NOTES FOR SNAPCLIENT INTEGRATION:
# ============================================================
# When using with snapclient, configure speaker with:
#
# speaker:
#   - platform: i2s_audio
#     id: speaker_id
#     dac_type: external
#     i2s_dout_pin: ${i2s_dout_pin}
#     audio_dac: tas58xx_dac
#     channel: stereo
#     sample_rate: 48000
#
# Or for direct snapclient integration:
#
# snapclient:
#   hostname: your.server.ip
#   port: 1704
#   name: ${friendly_name}
#   i2s_dout_pin: ${i2s_dout_pin}
#   audio_dac: tas58xx_dac
#
# IMPORTANT: Add startup sound file for clock initialization:
# media_player:
#   - platform: speaker
#     id: media_player_id
#     files:
#       - id: startup_sync_sound
#         file: https://github.com/mrtoy-me/esphome-tas5805m/raw/main/components/tas5805m/tas5805m_boot_louder.flac
# ============================================================
# SOFTWARE EQ COMPATIBILITY:
# - TAS5825M has HARDWARE DSP with 15-band parametric EQ
# - NOT compatible with boards/software/soft-eq-18band.yaml
# - CPU overhead: 0% - all EQ processing done in DAC chip
# - Better signal quality (DSP before D/A conversion)
# ============================================================
