# ============================================================
# Amped ESP32-S3 Plus - Example Configuration
# ============================================================
# This example shows how to use the Amped-ESP32-S3-Plus board profile
# with the 18-band software EQ package from GitHub.
#
# Hardware: Amped-ESP32-S3-Plus (Rev. K+)
# - ESP32-S3 @ 240MHz with 8MB Flash + 8MB PSRAM (octal)
# - PCM5122 DAC (I2C controlled, 24-bit 192kHz)
# - TPA3128 Amplifier (22W @ 8Î©)
# - Optional: OLED display, RGB LED, IR receiver, Ethernet
#
# Documentation: https://github.com/farmed-switch/c-MM-esphome-snapclient
# ============================================================

substitutions:
  name: snapcast-client-01
  friendly_name: Snapcast Client
  task_stack_in_psram: "true"  # CRITICAL for ESP32-S3 (false only for vanilla ESP32)
  repo_url_shorthand: github://farmed-switch/c-MM-esphome-snapclient

# Import board profile and software EQ from GitHub as packages (must be a list)
# NOTE: packages URL must be literal strings, cannot use substitutions
packages:
  - url: https://github.com/farmed-switch/c-MM-esphome-snapclient
    ref: board-profiles
    files: [boards/sonocotta/amped-esp32-s3-plus.yaml]
    refresh: 0s
  - url: https://github.com/farmed-switch/c-MM-esphome-snapclient
    ref: board-profiles
    files: [boards/software/soft-eq-18band.yaml]
    refresh: 0s

# Override esp32 config to add DSP settings on top of board profile's hardware config
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    log_level: info
    sdkconfig_options:
      # ESP32-S3 hardware settings (from board profile)
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"
      # USB Serial for ESP32-S3 (REQUIRED for debug output)
      CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: "y"
      CONFIG_ESP_CONSOLE_SECONDARY_NONE: "y"
      # DSP settings for snapclient software EQ
      CONFIG_SNAPCLIENT_DSP_FLOW_STEREO: "n"
      CONFIG_SNAPCLIENT_DSP_FLOW_BASS_TREBLE_EQ: "n"
      CONFIG_USE_DSP_PROCESSOR: "y"
      CONFIG_DSP_OPTIMIZED: "y"
      CONFIG_DSP_MAX_FFT_SIZE: "4096"

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

network:
  enable_ipv6: true

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  min_version: 2025.7.0
  platformio_options:
    board_build.flash_mode: dio

logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG  # Enable USB serial for ESP32-S3

debug:
  update_interval: 5s

safe_mode:
  disabled: true

mdns:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 20dB

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80
  version: 3

api:
  encryption:
    key: !secret api_encryption_key

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Stockholm"  # Change to your timezone
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
    update_interval: 6h
    on_time_sync:
      then:
        - logger.log: "Time synchronized with NTP!"

external_components:
  - source: ${repo_url_shorthand}@main
    components: [ snapclient ]
    refresh: 0s

# NOTE: i2s_audio is already defined in board profile
# (GPIO15=LRCLK, GPIO14=BCLK from amped-esp32-s3-plus.yaml)

snapclient:
  hostname: !secret snapserver_host  # Your Snapcast server IP/hostname
  port: 1704
  name: ${friendly_name}
  i2s_dout_pin: GPIO16
  audio_dac: pcm5122_dac  # CRITICAL: Link to PCM5122 from board profile

# Additional sensors for monitoring
sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s
  - platform: internal_temperature
    name: "${friendly_name} CPU Temperature"
    update_interval: 60s
  - platform: template
    name: "${friendly_name} Free Heap"
    entity_category: diagnostic
    lambda: |-
      return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024.0;
    unit_of_measurement: 'kB'
    update_interval: 10s
  - platform: template
    name: "${friendly_name} Free PSRAM"
    entity_category: diagnostic
    lambda: |-
      return heap_caps_get_free_size(MALLOC_CAP_SPIRAM) / 1024.0;
    unit_of_measurement: 'kB'
    update_interval: 10s
  - platform: debug
    loop_time:
      name: "${friendly_name} Loop Time"

button:
  - platform: restart
    name: "${friendly_name} REBOOT"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
    mac_address:
      name: "${friendly_name} MAC"
  - platform: version
    name: "${friendly_name} ESPHome Version"
  - platform: template
    name: "${friendly_name} Time"
    entity_category: diagnostic
    lambda: |-
      auto time = id(sntp_time).now();
      if (!time.is_valid()) {
        return {"Syncing..."};
      }
      char buf[20];
      snprintf(buf, sizeof(buf), "%04d-%02d-%02d %02d:%02d:%02d",
        time.year, time.month, time.day_of_month,
        time.hour, time.minute, time.second);
      return {buf};
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

# ==============================================================
# NOTES:
# ==============================================================
# 1. All EQ controls (18 bands + switch + presets) are 
#    automatically included via the soft_eq package above!
# 
# 2. The board package includes:
#    - ESP32-S3 configuration with PSRAM
#    - I2S audio pins (BCK=GPIO14, WS=GPIO15, DOUT=GPIO16)
#    - PCM5122 DAC configuration (I2C @ 0x4D)
#    - DAC enable switch (restore_mode: ALWAYS_ON)
#    - Amplifier enable switch (GPIO17, restore_mode: ALWAYS_OFF)
#
# 3. Create a secrets.yaml file with:
#    wifi_ssid: "YourWiFiSSID"
#    wifi_password: "YourWiFiPassword"
#    ota_password: "YourOTAPassword"
#    api_encryption_key: "YourAPIKey"
#    snapserver_host: "192.168.1.100"  # Your Snapcast server
#
# 4. For ESP32-S3 boards, ALWAYS include:
#    - task_stack_in_psram: "true"
#    - CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: "y"
#    - logger.hardware_uart: USB_SERIAL_JTAG
#
# ==============================================================
# OPTIONAL FEATURES (Amped-ESP32-S3-Plus Hardware)
# ==============================================================
# The Plus model includes additional peripherals that can be
# activated by uncommenting the relevant sections below.
#
# Hardware available on Amped-ESP32-S3-Plus:
# - RGB LED (GPIO21) - WS2812 addressable LED
# - IR Receiver (GPIO07) - Infrared remote control input
# - OLED Display (SPI) - Optional screen via GPIO12/11/13/47/38/48
# - Ethernet (W5500) - Optional wired network via GPIO10/6/5
#
# GPIO Pins (from board profile substitutions):
# - rgb_led_pin: GPIO21
# - ir_rx_pin: GPIO07
# - spi_clk_pin: GPIO12, spi_mosi_pin: GPIO11, spi_miso_pin: GPIO13
# - display_cs_pin: GPIO47, display_dc_pin: GPIO38, display_reset_pin: GPIO48
# - eth_cs_pin: GPIO10, eth_interrupt_pin: GPIO6, eth_reset_pin: GPIO5
#
# ==============================================================

# ============================================================================
# OPTIONAL: RGB LED (WS2812)
# ============================================================================
# Uncomment to enable the front RGB LED for status indication
#
# light:
#   - platform: esp32_rmt_led_strip
#     id: rgb_front_led
#     name: "${friendly_name} LED"
#     rgb_order: GRB
#     pin: GPIO21  # ${rgb_led_pin} from board profile
#     num_leds: 1
#     chipset: ws2812
#     default_transition_length: 0s
#     effects:
#       - pulse:
#           name: "Pulse"
#       - strobe:
#           name: "Strobe"

# ============================================================================
# OPTIONAL: IR Receiver
# ============================================================================
# Uncomment to enable infrared remote control reception
# Requires ESPHome remote_receiver component
#
# remote_receiver:
#   pin:
#     number: GPIO07  # ${ir_rx_pin} from board profile
#     inverted: true
#     mode:
#       input: true
#       pullup: true
#   dump: all  # Change to specific protocol after testing
#   # tolerance: 25%
#   # buffer_size: 10kb
#
# # Example: React to specific IR codes
# binary_sensor:
#   - platform: remote_receiver
#     name: "${friendly_name} IR Button Play"
#     nec:
#       address: 0x00FF
#       command: 0x00FF  # Replace with your remote's code
#     on_press:
#       - homeassistant.service:
#           service: media_player.media_play_pause
#           data:
#             entity_id: media_player.snapcast

# ============================================================================
# OPTIONAL: OLED Display (SSD1306 128x64 via SPI)
# ============================================================================
# Uncomment to enable OLED display showing IP, WiFi, etc.
# Requires ESPHome display component
#
# spi:
#   clk_pin: GPIO12   # ${spi_clk_pin}
#   mosi_pin: GPIO11  # ${spi_mosi_pin}
#   miso_pin: GPIO13  # ${spi_miso_pin}
#
# display:
#   - platform: ssd1306_spi
#     model: "SSD1306 128x64"
#     cs_pin: GPIO47    # ${display_cs_pin}
#     dc_pin: GPIO38    # ${display_dc_pin}
#     reset_pin: GPIO48 # ${display_reset_pin}
#     rotation: 0
#     lambda: |-
#       it.printf(0, 0, id(font_small), "${friendly_name}");
#       it.printf(0, 16, id(font_small), "IP: %s", id(wifi_ip).state.c_str());
#       it.printf(0, 32, id(font_small), "WiFi: %.0fdBm", id(wifi_signal_db).state);
#       it.printf(0, 48, id(font_small), "Heap: %.0fkB", id(free_heap).state);
#
# font:
#   - file: "fonts/arial.ttf"
#     id: font_small
#     size: 12

# ============================================================================
# OPTIONAL: Ethernet (W5500)
# ============================================================================
# Uncomment to enable wired Ethernet instead of WiFi
# NOTE: If using Ethernet, comment out or remove the wifi: section above
#
# spi:  # If not already defined for display
#   clk_pin: GPIO12
#   mosi_pin: GPIO11
#   miso_pin: GPIO13
#
# ethernet:
#   type: W5500
#   clk_pin: GPIO12   # Shared with SPI
#   mosi_pin: GPIO11  # Shared with SPI
#   miso_pin: GPIO13  # Shared with SPI
#   cs_pin: GPIO10    # ${eth_cs_pin}
#   interrupt_pin: GPIO6  # ${eth_interrupt_pin}
#   reset_pin: GPIO5  # ${eth_reset_pin}
#   # Use static IP or DHCP
#   # manual_ip:
#   #   static_ip: 192.168.1.200
#   #   gateway: 192.168.1.1
#   #   subnet: 255.255.255.0

# ============================================================================
# TROUBLESHOOTING
# ============================================================================
# No serial output?
#   - Ensure logger.hardware_uart: USB_SERIAL_JTAG is set
#   - Ensure CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: "y" in esp32.framework.sdkconfig_options
#   - Check baud rate: 115200
#
# No audio output?
#   - Verify snapserver is running and reachable
#   - Check snapclient hostname/port
#   - Ensure audio_dac: pcm5122_dac is set in snapclient
#   - Check DAC enable switch in Home Assistant
#
# EQ not working?
#   - Verify soft-eq-18band.yaml package is included
#   - Check CONFIG_USE_DSP_PROCESSOR: "y" in esp32.framework.sdkconfig_options
#   - Look for EQ entities in Home Assistant
#
# WiFi connection issues?
#   - Verify 2.4GHz WiFi (ESP32-S3 doesn't support 5GHz)
#   - Check SSID/password in secrets.yaml
#   - Try power_save_mode: none
#
# High loop time / lag?
#   - Disable debug: component
#   - Set logger level: INFO instead of DEBUG
#   - Check Free PSRAM sensor (should be >7MB free)
# ==============================================================
