# Example: Amped ESP32-S3 WITHOUT Software EQ (Minimal)
# Use this for lowest CPU usage and when you don't need equalization
#
# Flash this from ESPHome (Home Assistant or esphome.io)

substitutions:
  name: snapcast-amped-s3
  friendly_name: "Snapcast Amped S3"

# Include ONLY board hardware (no soft EQ)
packages:
  board: !include boards/sonocotta/amped-esp32-s3.yaml

# Application Configuration
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.7.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  on_boot: 
    priority: 600
    then:
      - lambda: |-
          esp_netif_set_hostname(esp_netif_get_handle_from_ifkey("WIFI_STA_DEF"), "${name}");
      - logger.log: "Waiting 30s for NTP sync..."
      - delay: 30s
      - switch.turn_on: enable_dac

# ESP32-S3 Framework (NO DSP - clean audio path)
esp32:
  framework:
    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"

logger:
  level: DEBUG

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 20dB

# Home Assistant API
api:

# OTA Updates
ota:
  - platform: esphome
    password: !secret ota_password

# Web Server
web_server:
  port: 80
  version: 3

# Time for NTP sync
time:
  - platform: sntp
    id: sntp_time
    timezone: "CET-1CEST,M3.5.0,M10.5.0/3"

# Snapclient Component
external_components:
  - source: github://farmed-switch/c-MM-esphome-snapclient@main
    components: [ snapclient ]
    refresh: 0s

snapclient:
  hostname: !secret snapserver_ip
  port: 1704
  name: ${friendly_name}
  i2s_dout_pin: GPIO16

# Minimal sensors
sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
